name: Run Tests and Create .env.development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Create .env.development file
        run: |
          echo "PORT=3000" >> .env.development
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env.development
          echo "NODE_ENV=development" >> .env.development
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.development
          echo "ORIGIN=${{ secrets.ORIGIN }}" >> .env.development
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env.development
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env.development
          echo "TWILIO_SERVICE_SID=${{ secrets.TWILIO_SERVICE_SID }}" >> .env.development

      - name: Run Jest tests
        run: npm test
