name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey! Thanks for opening an issue. Welcoming to the Swifty Community"
        pr-message: "Hey! Thanks for opening an issue. Welcoming to the Swifty Community. Make sure your PR fulfills the checks"
